---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  aws_config:
    file: ./src/secrets/aws_config
  database_creds:
    file: ./src/secrets/database_creds.yml

services:
  trustymail_reporter:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: cisagov/trustymail_reporter
    init: true
    restart: "no"
    secrets:
      - source: aws_config
        target: aws_config
      - source: database_creds
        target: database_creds.yml
  redis:
    image: redis:alpine
